//contacts
export const GET_CONTACTS = 'GET_CONTACTS';
export const ADD_NEW_CONTACT = 'ADD_NEW_CONTACT';

export const SET_CONTACTS = 'SET_CONTACTS';
export const SET_NEW_CONTACT = 'SET_NEW_CONTACT';

export const DELETE_CONTACT = 'DELETE_CONTACT';
export const SET_DELETE_CONTACT = 'SET_DELETE_CONTACT';